src/Entity/Logboek.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\LogboekRepository")
 */
class Logboek
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $userId;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $brief_nr;

    /**
     * @ORM\Column(type="datetime")
     */
    private $datum;

    /**
     * @ORM\Column(type="integer")
     */
    private $chauffeurId;

    /**
     * @ORM\Column(type="integer")
     */
    private $trucId;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $kubs;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $laadplaats;

    /**
     * @ORM\Column(type="time")
     */
    private $vertrektijd;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $bestemming;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $evenement;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUserId(): ?int
    {
        return $this->userId;
    }

    public function setUserId(int $userId): self
    {
        $this->userId = $userId;

        return $this;
    }

    public function getBriefNr(): ?string
    {
        return $this->brief_nr;
    }

    public function setBriefNr(string $brief_nr): self
    {
        $this->brief_nr = $brief_nr;

        return $this;
    }

    public function getDatum(): ?\DateTimeInterface
    {
        return $this->datum;
    }

    public function setDatum(\DateTimeInterface $datum): self
    {
        $this->datum = $datum;

        return $this;
    }

    public function getChauffeurId(): ?int
    {
        return $this->chauffeurId;
    }

    public function setChauffeurId(int $chauffeurId): self
    {
        $this->chauffeurId = $chauffeurId;

        return $this;
    }

    public function getTrucId(): ?int
    {
        return $this->trucId;
    }

    public function setTrucId(int $trucId): self
    {
        $this->trucId = $trucId;

        return $this;
    }

    public function getKubs(): ?string
    {
        return $this->kubs;
    }

    public function setKubs(string $kubs): self
    {
        $this->kubs = $kubs;

        return $this;
    }

    public function getLaadplaats(): ?string
    {
        return $this->laadplaats;
    }

    public function setLaadplaats(string $laadplaats): self
    {
        $this->laadplaats = $laadplaats;

        return $this;
    }

    public function getVertrektijd(): ?\DateTimeInterface
    {
        return $this->vertrektijd;
    }

    public function setVertrektijd(\DateTimeInterface $vertrektijd): self
    {
        $this->vertrektijd = $vertrektijd;

        return $this;
    }

    public function getBestemming(): ?string
    {
        return $this->bestemming;
    }

    public function setBestemming(string $bestemming): self
    {
        $this->bestemming = $bestemming;

        return $this;
    }

    public function getEvenement(): ?string
    {
        return $this->evenement;
    }

    public function setEvenement(string $evenement): self
    {
        $this->evenement = $evenement;

        return $this;
    }
}

src/Entity/User.php
<?php
// src/Entity/User.php

namespace App\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="fos_user")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }
}

src/Form/LogboekType.php
<?php

namespace App\Form;

use App\Entity\Logboek;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class LogboekType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('userId')
            ->add('brief_nr')
            ->add('datum')
            ->add('chauffeurId')
            ->add('trucId')
            ->add('kubs')
            ->add('laadplaats')
            ->add('vertrektijd')
            ->add('bestemming')
            ->add('evenement')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Logboek::class,
        ]);
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    /**
     * @Route("/", name="default")
     */
    public function index()
    {
        return $this->render('default/index.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
    }
}

src/Controller/LogboekController.php
<?php

namespace App\Controller;

use App\Entity\Logboek;
use App\Form\LogboekType;
use App\Repository\LogboekRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/logboek")
 */
class LogboekController extends AbstractController
{
    /**
     * @Route("/", name="logboek_index", methods={"GET"})
     */
    public function index(LogboekRepository $logboekRepository): Response
    {
        return $this->render('logboek/index.html.twig', [
            'logboeks' => $logboekRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="logboek_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $logboek = new Logboek();
        $logboek->setDatum(new \DateTime('now'));
        $form = $this->createForm(LogboekType::class, $logboek);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($logboek);
            $entityManager->flush();

            return $this->redirectToRoute('logboek_index');
        }

        return $this->render('logboek/new.html.twig', [
            'logboek' => $logboek,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="logboek_show", methods={"GET"})
     */
    public function show(Logboek $logboek): Response
    {
        return $this->render('logboek/show.html.twig', [
            'logboek' => $logboek,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="logboek_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Logboek $logboek): Response
    {
        $form = $this->createForm(LogboekType::class, $logboek);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('logboek_index', [
                'id' => $logboek->getId(),
            ]);
        }

        return $this->render('logboek/edit.html.twig', [
            'logboek' => $logboek,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="logboek_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Logboek $logboek): Response
    {
        if ($this->isCsrfTokenValid('delete'.$logboek->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($logboek);
            $entityManager->flush();
        }

        return $this->redirectToRoute('logboek_index');
    }
}

templates/base.html.twig
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>{% block title %}Welcome!{% endblock %}</title>

    {% block stylesheets %}{% endblock %}

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

</head>
<body>
<header>
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
        <a class="navbar-brand" href="{{ path('default') }}">Dashboard</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link disabled" href="{{ path('logboek_index') }}">Mijn logboeken</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href='{{ path('fos_user_registration_register') }}'>Registreer</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="/logout">Uitloggen</a>
                </li>
            </ul>
        </div>
    </nav>
</header>
{% block fos_user_content %}{% endblock %}

{% block body %}dit word de inhoud van de site.{% endblock %}

<!-- FOOTER -->
<footer class="container">

</footer>
</main>
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

{% block javascripts %}{% endblock %}

</body>
</html>

templates/default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello DefaultController!{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <div class="wrapper">
        <h1>This is the Homepage</h1>
    </div>
{% endblock %}

templates/logboek/_delete_form.html.twig
<form method="post" action="{{ path('logboek_delete', {'id': logboek.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ logboek.id) }}">
    <button class="btn">Delete</button>
</form>

templates/logboek/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/logboek/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Logboek{% endblock %}

{% block body %}
    <h1>Edit Logboek</h1>

    {{ include('logboek/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('logboek_index') }}">back to list</a>

    {{ include('logboek/_delete_form.html.twig') }}
{% endblock %}

templates/logboek/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logboek index{% endblock %}

{% block body %}
    <h1>Logboek index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>UserId</th>
                <th>Brief_nr</th>
                <th>Datum</th>
                <th>ChauffeurId</th>
                <th>TrucId</th>
                <th>Kubs</th>
                <th>Laadplaats</th>
                <th>Vertrektijd</th>
                <th>Bestemming</th>
                <th>Evenement</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for logboek in logboeks %}
            <tr>
                <td>{{ logboek.id }}</td>
                <td>{{ logboek.userId }}</td>
                <td>{{ logboek.briefNr }}</td>
                <td>{{ logboek.datum ? logboek.datum|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ logboek.chauffeurId }}</td>
                <td>{{ logboek.trucId }}</td>
                <td>{{ logboek.kubs }}</td>
                <td>{{ logboek.laadplaats }}</td>
                <td>{{ logboek.vertrektijd ? logboek.vertrektijd|date('H:i:s') : '' }}</td>
                <td>{{ logboek.bestemming }}</td>
                <td>{{ logboek.evenement }}</td>
                <td>
                    <a href="{{ path('logboek_show', {'id': logboek.id}) }}">show</a>
                    <a href="{{ path('logboek_edit', {'id': logboek.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="12">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('logboek_new') }}">Create new</a>
{% endblock %}

templates/logboek/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Logboek{% endblock %}

{% block body %}
    <h1>Create new Logboek</h1>

    {{ include('logboek/_form.html.twig') }}

    <a href="{{ path('logboek_index') }}">back to list</a>
{% endblock %}

templates/logboek/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Logboek{% endblock %}

{% block body %}
    <h1>Logboek</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ logboek.id }}</td>
            </tr>
            <tr>
                <th>UserId</th>
                <td>{{ logboek.userId }}</td>
            </tr>
            <tr>
                <th>Brief_nr</th>
                <td>{{ logboek.briefNr }}</td>
            </tr>
            <tr>
                <th>Datum</th>
                <td>{{ logboek.datum ? logboek.datum|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>ChauffeurId</th>
                <td>{{ logboek.chauffeurId }}</td>
            </tr>
            <tr>
                <th>TrucId</th>
                <td>{{ logboek.trucId }}</td>
            </tr>
            <tr>
                <th>Kubs</th>
                <td>{{ logboek.kubs }}</td>
            </tr>
            <tr>
                <th>Laadplaats</th>
                <td>{{ logboek.laadplaats }}</td>
            </tr>
            <tr>
                <th>Vertrektijd</th>
                <td>{{ logboek.vertrektijd ? logboek.vertrektijd|date('H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Bestemming</th>
                <td>{{ logboek.bestemming }}</td>
            </tr>
            <tr>
                <th>Evenement</th>
                <td>{{ logboek.evenement }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('logboek_index') }}">back to list</a>

    <a href="{{ path('logboek_edit', {'id': logboek.id}) }}">edit</a>

    {{ include('logboek/_delete_form.html.twig') }}
{% endblock %}